### ISSUE TITLE
Yolo v10 version

### ISSUE THREAD

**Issue by fshemaj** [hsiangwei0903/Deep-EIoU#10]
Hello,

Thank you for all your work. Given the accuracy and latency of the new yolov10 model, are you planning to release a version trained on SportsMOT using yolov10 backbone instead of yolox?  
This would be super helpful!

I can't find the full version of the SportsMOT dataset. If you can share any link to it, that would be great too!

**Comment by hsiangwei0903** [comment]
Hi,

Sorry, we are not planning to update our detector bc we think the performance gain might not be significant between YOLOX and YOLOv10 (especially given the detection related metrics like MOTA and DetA are already pretty high). But feel free to use our code and incorporate it with YOLOv10.

**Comment by hsiangwei0903** [comment]
To get the full version of SportsMOT dataset, please follow [here](https://github.com/MCG-NJU/SportsMOT?tab=readme-ov-file#usage)
