### ISSUE TITLE
questions on reid implementation

### ISSUE THREAD

**Issue by ShonLy** [hsiangwei0903/Deep-EIoU#13]
Thank you for your great work.
I am tring to  reimplement your awesome job, so I want  to know what specific reid model you use in the paper, and what is the specific training command?

**Comment by hsiangwei0903** [comment]
We use OSNet as Reid model, and we use [https://github.com/KaiyangZhou/deep-person-reid](https://github.com/KaiyangZhou/deep-person-reid) for training.
