### ISSUE TITLE
Request for Example Script for Detection and Embedding Data Generation

### ISSUE THREAD

**Issue by 258863** [hsiangwei0903/Deep-EIoU#14]
Hello,

I hope this message finds you well. Could you please provide an example script for generating detection and embedding data? This would be incredibly helpful for us, especially if we are considering experimenting with a new dataset in your project.

Thank you for your assistance!

**Comment by hsiangwei0903** [comment]
Hi, you can modify demo.py and save the immediate results into desired format.
