### ISSUE TITLE
Kalman FIlter Understanding

### ISSUE THREAD

**Issue by FadhilRa** [hsiangwei0903/Deep-EIoU#17]
Is there any explanation about where, when, and how Kalman FIlter use in this Project???

**Comment by hsiangwei0903** [comment]
Kalman filter is not used as our main association method in our paper, although there might be some Kalman filter's code not fully cleaned up in our repo. See paper https://openaccess.thecvf.com/content/WACV2024W/RWS/papers/Huang_Iterative_Scale-Up_ExpansionIoU_and_Deep_Features_Association_for_Multi-Object_Tracking_WACVW_2024_paper.pdf
