### ISSUE TITLE
Waiting for the code and integration with Ultralytics YOLOv8 if possible

### ISSUE THREAD

**Issue by wagmi-admin** [hsiangwei0903/Deep-EIoU#2]
Yolov8 has support for both BotSort and ByteTrack as tracker. Post reading about Deep-EloU - I believe it will be a must have if configured with Yolov8 directly.

**Comment by hsiangwei0903** [comment]
Hello @wagmi-admin,
Thanks for your interest to our work, unfortunately we only provided YOLOX model trained on the SportsMOT dataset for now, but  you can use our code and switch the detector to YOLOv8.
