### ISSUE TITLE
Question regarding iterative EIoU

### ISSUE THREAD

**Issue by tteresi7** [hsiangwei0903/Deep-EIoU#3]
It's not really clear in the paper, you state that you iteratively calculate the EIoU over 0.7 with a step of 0.1 in the first round of matching.  However, what's not clear is at what value to you stopped iterating, and how you ultimately selected which EIoU iteration to use for the cost matrix's hungarian solving?

**Comment by hsiangwei0903** [comment]
Hello @tteresi7 ,

Thanks for your interest to our work. To answer your question, we conduct Hungarian matching in every round and we conduct two rounds of association in the first stage (high score matching) using different Expansion scale. I hope this answer your question, we have updated our ArXiv paper with more detailed explanation and please let me know if you have any question.

**Comment by tteresi7** [comment]
> Hello @tteresi7 ,
> 
> Thanks for your interest to our work. To answer your question, we conduct Hungarian matching in every round and we conduct two rounds of association in the first stage (high score matching) using different Expansion scale. I hope this answer your question, we have updated our ArXiv paper with more detailed explanation and please let me know if you have any question.

Thanks mate!
