### ISSUE TITLE
sportsMOT提交验证：Exception: Uploaded results are not one-to-one matches to the test set.

### ISSUE THREAD

**Issue by congyao123456** [hsiangwei0903/Deep-EIoU#4]
你好，遵循你的方法，经过sport_track.py和sport_interpolation.py之后，在interpolation文件夹下得到150个.txt文件，并进行压缩上传到sportsMOT出现：
Traceback (most recent call last):
  File "/tmp/codalab/tmpxw6bI2/run/program/evaluate_full_test.py", line 22, in 
    organize_input_full.process(input_dir)
  File "/tmp/codalab/tmpxw6bI2/run/program/organize_input_full.py", line 63, in process
    "Uploaded results are not one-to-one matches to the test set.")
Exception: Uploaded results are not one-to-one matches to the test set.
请问问题在哪，期待您的回复，不胜感激！

**Comment by hsiangwei0903** [comment]
Very likely that you zip the folder containing .txt files instead of directly zipping the .txt files. Please try to select all .txt files and zip them instead of zipping the folder.
