### ISSUE TITLE
How to obtain detection and embedding files on custom dataset？

### ISSUE THREAD

**Issue by blankTt** [hsiangwei0903/Deep-EIoU#5]

**Comment by hsiangwei0903** [comment]
Hi, 

You can modify the demo.py file to save your detection and embedding into your desired format.

**Comment by blankTt** [comment]
您好，我是马林涛，非常感谢您的来信，我会即时查收并回复~

**Comment by blankTt** [comment]
<img width="725" alt="微信图片_20240116104846" src="https://github.com/hsiangwei0903/Deep-EIoU/assets/40878805/14250d4d-2e39-4e72-a485-7e22f6f53967">
Thank you for your reply. May I ask if I only need to save the det and emb here

**Comment by blankTt** [comment]
<img width="725" alt="微信图片_20240116104846" src="https://github.com/hsiangwei0903/Deep-EIoU/assets/40878805/d9396626-6e12-45f5-a112-8fe71e55f734">

 Thank you for your reply. May I ask if I only need to save the det and emb here？

**Comment by hsiangwei0903** [comment]
Yes, I believe that should work.
