### ISSUE TITLE
YOLOX weights information

### ISSUE THREAD

**Issue by Robotmurlock** [hsiangwei0903/Deep-EIoU#6]
Hey,

Are the YOLOX weights you supplied [here](https://drive.google.com/drive/folders/1wItcb0yeGaxOS08_G9yRWBTnpVf0vZ2w) obtained by training only on train dataset or training on both training and validation dataset?

Thanks in advance :)

**Comment by Robotmurlock** [comment]
After performing the tracker evaluation, it is clear that it is trained on both train and validation sets. :)

**Comment by hsiangwei0903** [comment]
Hi @Robotmurlock , sorry I forgot to reply :(

Yes, it is trained on both train and val data. We found that only using training set resulted in inferior performance (as indicated in our paper)

![截圖 2024-01-31 下午11 09 22](https://github.com/hsiangwei0903/Deep-EIoU/assets/93310655/4012c5a2-47a2-4d05-b98c-1bee7368a499)

**Comment by Robotmurlock** [comment]
Thanks for the confirmation :)
