### ISSUE TITLE
YOLOX train only weights

### ISSUE THREAD

**Issue by Robotmurlock** [hsiangwei0903/Deep-EIoU#7]
Hey, 

Can you make the train-only YOLOX weights you used in paper public. They are useful for hyperparameter tuning on the validation dataset. 

Thanks in advance. :)

**Comment by hsiangwei0903** [comment]
Hi,

Sorry I did not work on this project anymore and the weight is not stored. But you can follow bytetrack's repo and hyperparameter setting to conduct training, this should resulted in a similar performance in our paper.

**Comment by Robotmurlock** [comment]
Hey,

Thanks for the response. I already resolved this issue.
